version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./dropbox-backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./dropbox-backend/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/dropbox
    depends_on:
      - mongo

volumes:
  mongo-data:
